language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - dv.riofrio@alumnos.upm.es
script:
#Test unitario y de integracion en develop
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.organization=DiegoRiofrio-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR


